name: Full CI - Python & Docker Lint

on:
  push:
    branches: [main, implementation-cicd]
  pull_request:
    branches: [main]

jobs:
  pylint:
    name: Pylint Linter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run Pylint
        run: |
          pylint $(git ls-files '*.py') --disable=C,R0801 --fail-under=5

  hadolint:
    name: Dockerfile Linter (Hadolint)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
