name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Node.js dependencies
      run: |
        npm ci

    - name: Run migrations and start Django
      run: |
        python manage.py migrate
        nohup python manage.py runserver 0.0.0.0:8000 &
        npx wait-on http://localhost:8000

    - name: Run Cypress
      uses: cypress-io/github-action@v5
      with:
        start: echo "server already started"
        wait-on: 'http://localhost:8000'
        wait-on-timeout: 60
        config: baseUrl=http://localhost:8000
