name: Scan Docker Image with Trivy

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  scan:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan Docker Image with Trivy (high & critical only)
        run: |
          trivy image --severity HIGH,CRITICAL ${{ secrets.DOCKERHUB_USERNAME }}/capucine-app:dev-${{ github.sha }}
