name: Lint Dockerfile with Hadolint

on:
  push:
    branches: [main, implementation-cicd]
  pull_request:
    branches: [main]

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
