name: Hadolint

on:
  push:
    branches: [main, implementation-cicd]
  pull_request:
    branches: [main]

jobs:
  hadolint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Dockerfile with Hadolint (official Docker image)
        run: |
          docker run --rm -i hadolint/hadolint < Dockerfile
