name: Lint Python Code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint django

      - name: Run Pylint
        run: |
          pylint **/*.py \
            --disable=C0114,C0116,C0115,C0304,C0303,C0301,C0411,C0209,R0903,R0801,R0901,W0611,W0612,W0621,W0613,E0401,E1101,E0307 \
            --fail-under=7
