name: Lint Python Code

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint django

      - name: Run Pylint
        run: |
          pylint **/*.py \
            --disable=C0114,C0116,R0903,R0801,W0613,E0401,E1101 \
            --fail-under=7
