name: SBOM Generation and Analysis

on: [push, pull_request]

jobs:
  sbom:
    runs-on: ubuntu-latest
    name: Generate SBOM and scan with Grype

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM with Syft
        run: |
          syft dir:. -o json > sbom.syft.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.syft.json

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan SBOM with Grype
        run: |
          grype sbom:sbom.syft.json -o table

      - name: Upload Grype scan result
        uses: actions/upload-artifact@v4
        with:
          name: grype-report
          path: sbom.syft.json
