name: Security Audit with ZAP

on:
    workflow_run:
      workflows: ["Deploy"]
      types:
        - completed

jobs:
  zap-audit:
    name: Run DAST Scan via OWASP ZAP
    runs-on: ubuntu-latest

    steps:
    - name: Clone source code
      uses: actions/checkout@v4

    - name: Prepare Docker build
      uses: docker/setup-buildx-action@v3

    - name: Launch App in Background
      run: |
        echo "version: '3'
        services:
          web:
            build: .
            ports:
              - '8080:8080'" > docker-compose.yml

        docker compose up -d
        sleep 15  # Wait for server to be reachable

    - name: Execute ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.14.0
      with:
        target: 'http://localhost:8080'
        allow_issue_writing: false
        fail_action: false

    - name: Archive ZAP Results
      uses: actions/upload-artifact@v4
      with:
        name: zap-dast-results
        path: |
          report.html
          report.json
        retention-days: 10

    - name: Shutdown services
      if: always()
      run: docker compose down
